---
- hosts: remote
  become: yes
  tasks:
  - name: install open jdk
    yum:
      name: java-1.8.0-openjdk.x86_64
      state: present
  - name: install tomcat 7
    yum:
      name: tomcat
      state: present
  - name: download openmrs to webapps
    get_url:
      url: https://excellmedia.dl.sourceforge.net/project/openmrs/releases/OpenMRS_Platform_2.0.5/openmrs.war
      dest: /usr/share/tomcat/webapps/openmrs.war
  - name: enable and start command
    service:
      name: tomcat
      state: started
      enabled: yes 
